### ISSUE TITLE
error message during installation 

### ISSUE THREAD

**Issue by PhreeMason** [learn-co/learn-co#83]
Hello I get this error message during installation 

> ERROR:  While executing gem ... (Errno::EINVAL)
>     Invalid argument @ rb_sysopen - C:/Ruby24/lib/ruby/gems/2.4.0/gems/learn-gen
> erate-1.0.16/lib/templates/ios/.liftoff/templates/<%= prefix %>AppDelegate.h

**Comment by andrewtrent** [comment]
Having the same issue:

`PS C:\ruby23> gem install learn-generate --verbose --backtrace
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=learn-generate
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/.gitignore
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/.rspec
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/Gemfile
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/LICENSE.txt
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/README.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/Rakefile
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/bin/learn-generate
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/learn-generate.gemspec
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/file_finder.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/helpers/dot-learn-helper.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/helpers/gemfile-helper.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/helpers/template-helper.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/ios_lab.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/ios_lab/liftoff_backup.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/template_loader.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/template_maker.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/learn_generate/version.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/.gitignore
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/.rspec
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/CONTRIBUTING.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/LICENSE.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/README.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/Rakefile
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/app/models/sample-class.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/config/environment.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/db/migrations/.keep
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/lib/support/connection_adapter.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/lib/support/db_registry.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/activerecord/spec/spec_helper.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/.gitignore
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/.rspec
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/CONTRIBUTING.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/LICENSE.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/README.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/bin/runner.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/lib/environment.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/lib/lab-name/cli.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/command-line/spec/spec_helper.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/.gitignore
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/CONTRIBUTING.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/LICENSE.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/README.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/css/style.css
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/images/.keep
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/front-end/index.html
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/.gitignore
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/.rspec
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/CONTRIBUTING.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/LICENSE.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/README.md
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/lib/file.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/fundamental-ruby/spec/spec_helper.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/ios/.liftoff/.liftoffrc
C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/ios/.liftoff/templates/.learn
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_sysopen - C:/Ruby23/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/ios/.liftoff/templates/<%= prefix %>AppDelegate.h
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:381:in `initialize'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:381:in `open'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:381:in `block (2 levels) in extract_tar_gz'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:363:in `block in extract_tar_gz'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:457:in `block in open_tar_gz'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:454:in `wrap'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:454:in `open_tar_gz'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:362:in `extract_tar_gz'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:343:in `block (2 levels) in extract_files'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:340:in `block in extract_files'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package/file_source.rb:30:in `open'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/package.rb:337:in `extract_files'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/installer.rb:768:in `extract_files'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/installer.rb:295:in `install'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/resolver/specification.rb:97:in `install'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request_set.rb:166:in `block in install'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request_set.rb:156:in `each'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request_set.rb:156:in `install'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:250:in `install_gem'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
        C:/Ruby23/bin/gem.cmd:29:in `<main>'`

**Comment by oli-gra** [comment]
Ditto on W10P with Ruby 2.3..3:
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_sysopen - C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/learn-generate-1.0.16/lib/templates/ios/.liftoff/templates/<%= prefix %>AppDelegate.h

**Comment by ebonyash15** [comment]
I was also having the same issue with running `gem install learn-co`.

I partially fixed this by running the command from the gems website `gem install learn-co -v 1.0.4`, however, when then running `learn whoami` I get the following error:

```
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/learn-co-1.0.4/lib/learn/username_parser.rb:10:in `gets': No such file or directory @ rb_sysopen - whoami (Errno::ENOENT)
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/learn-co-1.0.4/lib/learn/username_parser.rb:10:in `gets'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/learn-co-1.0.4/lib/learn/username_parser.rb:10:in `get_username'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/learn-co-1.0.4/bin/learn:11:in `<top (required)>'
        from C:/Ruby26-x64/bin/learn:23:in `load'
        from C:/Ruby26-x64/bin/learn:23:in `<main>'
Enter your github username:
```

which basically means they don't bother to check the directory so that's why I'm getting this error :/

**Comment by ItzelOrtiz** [comment]
git won't install any of the gems but Ubuntu did. However, Ubuntu won't show me the proper file locations when I type ls as git does.
